<?php

/**
 * AdminsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Admins');
    }
}