<?php

/**
 * AlbumSongsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumSongsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumSongsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlbumSongs');
    }
}