<?php

/**
 * AlbumsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Albums');
    }
}