<?php

/**
 * FiltersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FiltersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FiltersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Filters');
    }
}