<?php

/**
 * ProductImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductImages');
    }
}