<?php

/**
 * UserSongsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSongsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserSongsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserSongs');
    }
}